### PR TITLE
Removed rotate for pillar node

### PR DESCRIPTION
**Pull request by TumeniNodes**
Please review these changes.
I removed the rotate on placement for the pillar node.

### CODE REVIEW

**Comment by sofar** [comment]
I can't merge this. There is so much wrong with this commit... Did you use the "file upload" method in github?

Please, follow this guide to learn how to make good PRs in git/github: https://forum.minetest.net/viewtopic.php?f=3&t=14262

**Comment by sofar** [comment]
Can you redo this?

**Comment by EvergreenTheTree** [comment]
Please don't make two separate changes in a single pull request.  This does more than just remove the old horizontal pillar code, it also changes the formatting.  Those should be separate pull requests.  Also, you need to redo your pull request because of some recent changes which overlap with yours.

#### Side Note:

In general, pull requests which change the existing code formatting aren't well received.  What matters with indentation and formatting is that it is consistent throughout the project, not that it matches what you personally like best.

**Comment by VanessaE** [comment]
:-1: I am not in favor of removing rotation for the pillar.  It was supposed to behave something like a tree trunk does, in that it can be laid horizontally if the builder wants to.

**Comment by EvergreenTheTree** [comment]
I didn't even notice that it removed rotation entirely, I thought it just removed the old horizontal node that was used before 6d facedir.  I guess I didn't take a close enough look.  Definitely won't merge.  _(I also just noticed that it changes the dig noises to stone, which I don't like either)_

**Comment by sofar** [comment]
Let's just close this, the intended change isn't desired, and the PR itself contains unrelated changes.

**Comment by TumeniNodes** [comment]
I apologize for any issues this caused, or if my improper means of
submitting the PR caused any offense. I had made the changes based on the
fact when I added quartz to the angles walls, when placed next to another
quarts pillar node, the rotation kicks in and alters the vertical pillar.
A lesson learned.

**Pull request closed without merging**
